import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import ts from 'typescript';
async function load(path, deps, logs = []) {
  const code = ts.transpileModule(await readFile(new URL('../'+path, import.meta.url),'utf8'), {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;
  const loaded={exports:{}};
  new Function('require','module','exports','console',code)(id=>{assert.ok(id in deps,id);return deps[id]},loaded,loaded.exports,{info:x=>logs.push(x),error:x=>logs.push(x)});
  return loaded.exports;
}
const id='10000000-0000-0000-0000-000000000001';
const form=(overrides={})=>{const f=new FormData();for(const [k,v] of Object.entries({id,status:'CLOSED',...overrides}))f.set(k,v);return f};
async function server(authorized=true){
  let record={id,shopId:'shop-a',status:'NEW',preferredContactMethod:'TEXT',notification:{reads:[{userId:'other'}]},source:'CONTACT',name:'Synthetic',internalNote:null};
  const logs=[],emails=[],writes=[];
  const tx={marketingLead:{updateMany:async({where,data})=>{writes.push({where,data});if(where.id!==id||where.shopId!==record.shopId)return {count:0};record={...record,...data};return {count:1}},findFirstOrThrow:async()=>record}};
  const actions=await load('src/app/(app)/leads/manage-actions.ts',{'next/cache':{revalidatePath(){}},'@/generated/prisma/client':{MarketingLeadStatus:Object.fromEntries(['NEW','CONTACTED','SCHEDULED','CONVERTED','CLOSED'].map(x=>[x,x]))},'@/lib/permissions':{requirePermission:async p=>{assert.equal(p,'manage_marketing_leads');if(!authorized)throw Error('Denied');return {membership:{shopId:'shop-a'}}}},'@/lib/prisma':{prisma:{$transaction:fn=>fn(tx)}},'@/lib/marketing-lead-notifications':{notifyScheduledMarketingLead:async r=>emails.push(r)}},logs);
  return {save:actions.updateLeadStatus,get:()=>structuredClone(record),logs,emails,writes};
}
test('NEW → CONTACTED → CLOSED persists and changes only management fields',async()=>{const h=await server();const before=h.get();for(const status of ['CONTACTED','CLOSED']){await h.save(form({status,shopId:'foreign',userId:'foreign',preferredContactMethod:'EMAIL',internalNote:'x'.repeat(3100)}));assert.equal(h.get().status,status)}assert.equal(h.get().internalNote.length,3000);for(const k of ['preferredContactMethod','notification','source','name'])assert.deepEqual(h.get()[k],before[k]);assert.equal(h.emails.length,0);assert(h.writes.every(w=>w.where.shopId==='shop-a'));assert(h.logs.some(l=>l.result==='persisted'));});
test('NEW → CLOSED remains CLOSED on subsequent reads',async()=>{const h=await server();await h.save(form());assert.equal(h.get().status,'CLOSED');assert.equal(h.get().status,'CLOSED')});
for(const values of [{id:'invalid'},{id:'10000000-0000-0000-0000-000000000099'},{status:'INVALID'},{status:'SCHEDULED'},{status:'SCHEDULED',scheduledDate:'2026-10-01'},{status:'SCHEDULED',scheduledTime:'10:00'}])test('rejects invalid/cross-shop save '+JSON.stringify(values),async()=>{const h=await server();await assert.rejects(h.save(form(values)));assert.equal(h.get().status,'NEW');assert.equal(h.emails.length,0)});
test('unauthorized session cannot update',async()=>{const h=await server(false);await assert.rejects(h.save(form()));assert.equal(h.writes.length,0);assert.equal(h.logs.at(-1).stage,'authorization')});
test('SCHEDULED preserves confirmation email and schedule fields',async()=>{const h=await server();await h.save(form({status:'SCHEDULED',scheduledDate:'2026-10-01',scheduledTime:'10:30'}));assert.equal(h.emails.length,1);assert.equal(h.get().scheduledDate.toISOString(),'2026-10-01T00:00:00.000Z');assert.equal(h.get().scheduledTime,'10:30')});
test('safe logs exclude arbitrary submitted data and raw error details',async()=>{const h=await server();await assert.rejects(h.save(form({id:'private@example.test',status:'private note',internalNote:'secret note'})));const serialized=JSON.stringify(h.logs);assert.doesNotMatch(serialized,/private|secret/);for(const l of h.logs)assert(Object.keys(l).every(k=>['event','leadId','requestedStatus','result','stage'].includes(k)))});
async function client(){let callback,state='idle',pending=false;const ref={current:false},toasts=[];let save=async()=>{};const jsx=(type,props)=>({type,props});const {LeadManagementForm}=await load('src/components/lead-management-form.tsx',{'react/jsx-runtime':{jsx,jsxs:jsx},react:{useRef:()=>ref,useActionState:fn=>{callback=fn;return[state,fn,pending]}},'react-hot-toast':{default:{success:m=>toasts.push(m),error:m=>toasts.push(m)}},'@/app/(app)/leads/manage-actions':{updateLeadStatus:f=>save(f)}});return{render:()=>LeadManagementForm({children:'fields'}),run:f=>callback(state,f),setSave:fn=>{save=fn},setState:s=>{state=s},setPending:p=>{pending=p},ref,toasts}}
const nodes=t=>!t||typeof t!=='object'?[]:Array.isArray(t)?t.flatMap(nodes):[t,...nodes(t.props?.children)];
test('success/failure feedback and pending disabled save are accessible',async()=>{const h=await client();h.render();assert.equal(await h.run(form()),'saved');h.setState('saved');assert(nodes(h.render()).some(n=>n.props.role==='status'&&n.props.children==='Lead saved.'));h.setSave(async()=>{throw Error('secret database error')});assert.equal(await h.run(form()),'failed');h.setState('failed');assert(nodes(h.render()).some(n=>n.props.children==='Could not save the lead. Please try again.'));h.setPending(true);const tree=h.render();assert.equal(tree.props['aria-busy'],true);assert(nodes(tree).find(n=>n.type==='button').props.disabled);assert.doesNotMatch(JSON.stringify(h.toasts),/secret/)});
test('rapid duplicate submits are blocked and the guard resets after completion/failure',async()=>{const h=await client();const tree=h.render();let blocked=0;const event={preventDefault:()=>blocked++};tree.props.onSubmit(event);tree.props.onSubmit(event);assert.equal(blocked,1);await h.run(form());assert.equal(h.ref.current,false);tree.props.onSubmit(event);h.setSave(async()=>{throw Error('offline')});await h.run(form());assert.equal(h.ref.current,false)});
