import Link from "next/link";
import { notFound } from "next/navigation";
import { FormSubmitButton } from "@/components/form-submit-button";
import { getInvoiceForCurrentShop } from "@/lib/data/invoices";
import { isEditableOpenInvoice } from "@/lib/invoice-lifecycle";
import { formatMoney } from "@/lib/formatters";
import { addInvoiceLabor, addInvoicePart, deleteInvoiceLabor, deleteInvoicePart, updateInvoiceDetails, updateInvoiceLabor, updateInvoicePart } from "../../lifecycle-actions";

export const dynamic = "force-dynamic";
const input = "mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm font-normal";

export default async function EditInvoicePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const invoice = await getInvoiceForCurrentShop(id);
  if (!invoice || !isEditableOpenInvoice(invoice)) notFound();
  return <div className="space-y-6">
    <header><Link href={`/invoices/${invoice.id}`} className="text-sm font-semibold text-brand-primary">← Back to invoice</Link><h1 className="mt-4 text-3xl font-bold text-slate-950">Edit Invoice — RO #{invoice.repairOrderNumber}</h1><p className="mt-2 text-sm text-amber-800">This invoice is open. Saved changes recalculate totals and accounts receivable while preserving recorded payments.</p></header>
    <form action={updateInvoiceDetails} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><input type="hidden" name="invoiceId" value={invoice.id} /><h2 className="font-semibold text-slate-950">Customer Concerns &amp; Recommendations</h2><div className="mt-4 grid gap-4 lg:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Customer Complaint<textarea name="customerComplaint" rows={5} defaultValue={invoice.customerComplaint ?? ""} className={input} /></label><label className="text-sm font-semibold text-slate-700">Service Recommendation<textarea name="recommendation" rows={5} defaultValue={invoice.recommendation ?? ""} className={input} /></label></div><FormSubmitButton pendingLabel="Saving…" className="mt-4 rounded-lg bg-brand-primary px-4 py-2 text-sm font-semibold text-white">Save invoice details</FormSubmitButton></form>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold text-slate-950">Parts · {formatMoney(invoice.partsTotal)}</h2><div className="mt-4 space-y-3">{invoice.parts.map((part) => <form key={part.id} action={updateInvoicePart} className="grid gap-3 rounded-xl border border-slate-200 p-4 md:grid-cols-[1fr_7rem_8rem_auto] md:items-end"><input type="hidden" name="invoiceId" value={invoice.id} /><input type="hidden" name="partId" value={part.id} /><label className="text-sm font-semibold">Description<input required name="description" defaultValue={part.description} className={input} /></label><label className="text-sm font-semibold">Quantity<input required name="quantity" type="number" min="0.01" step="0.01" defaultValue={part.quantity.toString()} className={input} /></label><label className="text-sm font-semibold">Unit price<input required name="unitPrice" type="number" min="0" step="0.01" defaultValue={part.unitPrice.toString()} className={input} /></label><div className="flex gap-2"><FormSubmitButton pendingLabel="Saving…" className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Save</FormSubmitButton><FormSubmitButton formAction={deleteInvoicePart} pendingLabel="Deleting…" confirmMessage="Delete this invoice part?" className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700">Delete</FormSubmitButton></div></form>)}</div><form action={addInvoicePart} className="mt-5 grid gap-3 border-t border-slate-200 pt-5 md:grid-cols-[1fr_7rem_8rem_auto] md:items-end"><input type="hidden" name="invoiceId" value={invoice.id} /><label className="text-sm font-semibold">Description<input required name="description" className={input} /></label><label className="text-sm font-semibold">Quantity<input required name="quantity" type="number" min="0.01" step="0.01" defaultValue="1" className={input} /></label><label className="text-sm font-semibold">Unit price<input required name="unitPrice" type="number" min="0" step="0.01" className={input} /></label><FormSubmitButton pendingLabel="Adding…" className="rounded-lg bg-brand-primary px-3 py-2 text-sm font-semibold text-white">Add part</FormSubmitButton></form></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold text-slate-950">Labor · {formatMoney(invoice.laborTotal)}</h2><div className="mt-4 space-y-3">{invoice.labor.map((labor) => <form key={labor.id} action={updateInvoiceLabor} className="grid gap-3 rounded-xl border border-slate-200 p-4 md:grid-cols-[1fr_7rem_8rem_auto] md:items-end"><input type="hidden" name="invoiceId" value={invoice.id} /><input type="hidden" name="laborId" value={labor.id} /><label className="text-sm font-semibold">Description<input required name="description" defaultValue={labor.description} className={input} /></label><label className="text-sm font-semibold">Hours<input required name="hours" type="number" min="0.01" step="0.01" defaultValue={labor.hours.toString()} className={input} /></label><label className="text-sm font-semibold">Rate<input required name="hourlyRate" type="number" min="0" step="0.01" defaultValue={labor.hourlyRate.toString()} className={input} /></label><div className="flex gap-2"><FormSubmitButton pendingLabel="Saving…" className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Save</FormSubmitButton><FormSubmitButton formAction={deleteInvoiceLabor} pendingLabel="Deleting…" confirmMessage="Delete this labor line?" className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700">Delete</FormSubmitButton></div></form>)}</div><form action={addInvoiceLabor} className="mt-5 grid gap-3 border-t border-slate-200 pt-5 md:grid-cols-[1fr_7rem_8rem_auto] md:items-end"><input type="hidden" name="invoiceId" value={invoice.id} /><label className="text-sm font-semibold">Description<input required name="description" className={input} /></label><label className="text-sm font-semibold">Hours<input required name="hours" type="number" min="0.01" step="0.01" className={input} /></label><label className="text-sm font-semibold">Rate<input required name="hourlyRate" type="number" min="0" step="0.01" className={input} /></label><FormSubmitButton pendingLabel="Adding…" className="rounded-lg bg-brand-primary px-3 py-2 text-sm font-semibold text-white">Add labor</FormSubmitButton></form></section>
  </div>;
}
