import type { Metadata } from "next";
import Image from "next/image";
import { LeadForm } from "@/components/marketing/lead-form";
import { MarketingPageHero } from "@/components/marketing/page-hero";
import { TrackedCallLink } from "@/components/marketing/tracked-call-link";
import { getPublicShop, phoneHref, shopAddress } from "@/lib/marketing";
import { getMarketingMedia, getMarketingPage } from "@/lib/marketing-content";
import { getPublicSeoShop, localTitle, marketingMetadata } from "@/lib/marketing-seo";
export async function generateMetadata(): Promise<Metadata> { const shop = await getPublicSeoShop(); return marketingMetadata({ title: localTitle("Contact", shop), description: `Call ${shop.name}, get directions, review current hours, or send the shop a question about auto repair in ${shop.city ?? "the local area"}.`, path: "/contact", siteName: shop.name }); }
export default async function ContactPage({ searchParams }: { searchParams: Promise<{ sent?: string; error?: string }> }) { const [shop, query, page, media] = await Promise.all([getPublicShop(), searchParams, getMarketingPage("contact"), getMarketingMedia()]); const address = shopAddress(shop); const map = address ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}` : null; const locationMedia = media.filter((item) => item.slot === "contact-entrance" || item.slot === "contact-sign"); return <><MarketingPageHero eyebrow={page.eyebrow ?? "Contact"} title={page.title} description={page.description} />{locationMedia.length ? <section className="mx-auto grid max-w-6xl gap-6 px-4 pt-16 sm:px-6 md:grid-cols-2">{locationMedia.map((item) => <figure key={item.slot} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="relative aspect-[4/3]"><Image src={item.imageUrl} alt={item.alt} fill sizes="(min-width: 768px) 50vw, 100vw" className="object-cover" style={{ objectPosition: item.objectPosition ?? "center" }} /></div>{item.heading || item.body ? <figcaption className="p-5">{item.heading ? <h2 className="text-xl font-black">{item.heading}</h2> : null}{item.body ? <p className="mt-2 leading-7 text-slate-600">{item.body}</p> : null}</figcaption> : null}</figure>)}</section> : null}<section className="mx-auto grid max-w-6xl gap-8 px-4 py-16 sm:px-6 lg:grid-cols-[340px_1fr]"><aside className="rounded-3xl bg-slate-950 p-7 text-white"><h2 className="text-2xl font-black">{shop.name}</h2><dl className="mt-7 space-y-5 text-sm"><div><dt className="text-slate-400">Phone</dt><dd className="mt-1 font-bold">{shop.phone ? <TrackedCallLink href={phoneHref(shop.phone)} className="rounded-sm hover:text-orange-300 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-500/30">{shop.phone}</TrackedCallLink> : "Contact form available"}</dd></div><div><dt className="text-slate-400">Address</dt><dd className="mt-1 font-bold">{address || "Contact us for directions"}</dd></div><div><dt className="text-slate-400">Hours</dt><dd className="mt-1 whitespace-pre-wrap font-bold leading-6">{shop.hours}</dd></div></dl>{map && <a href={map} target="_blank" rel="noreferrer" className="mt-7 block rounded-xl bg-white px-4 py-3 text-center font-black text-slate-950 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-500/30">Get Directions</a>}</aside><div><h2 className="mb-5 text-2xl font-black">Send a question</h2><LeadForm source="CONTACT" sent={query.sent === "1"} error={query.error === "1"} /></div></section></>; }
