"use client";

import { useEffect, useId, useRef } from "react";
import { createPortal } from "react-dom";

export function ConfirmDialog({ open, title, description, confirmLabel = "Confirm", cancelLabel = "Cancel", destructive = false, pending = false, onConfirm, onCancel }: { open: boolean; title: string; description: string; confirmLabel?: string; cancelLabel?: string; destructive?: boolean; pending?: boolean; onConfirm: () => void; onCancel: () => void }) {
  const titleId = useId(); const descriptionId = useId(); const cancelRef = useRef<HTMLButtonElement>(null); const confirmRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (!open) return; cancelRef.current?.focus(); const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape" && !pending) onCancel(); if (event.key === "Tab") { const active = document.activeElement; if (event.shiftKey && active === cancelRef.current) { event.preventDefault(); confirmRef.current?.focus(); } else if (!event.shiftKey && active === confirmRef.current) { event.preventDefault(); cancelRef.current?.focus(); } } }; document.addEventListener("keydown", onKeyDown); const overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", onKeyDown); document.body.style.overflow = overflow; }; }, [open, pending, onCancel]);
  if (!open || typeof document === "undefined") return null;
  return createPortal(<div className="fixed inset-0 z-50 flex items-center justify-center p-4" role="presentation"><button type="button" tabIndex={-1} aria-label="Close confirmation" disabled={pending} onClick={onCancel} className="absolute inset-0 cursor-default bg-slate-950/50 backdrop-blur-[1px]" /><section role="alertdialog" aria-modal="true" aria-labelledby={titleId} aria-describedby={descriptionId} className="relative w-full max-w-md rounded-2xl border border-slate-200 bg-white p-6 shadow-2xl"><div className={`flex size-11 items-center justify-center rounded-full text-xl font-bold ${destructive ? "bg-red-100 text-red-700" : "bg-sky-100 text-sky-700"}`}>{destructive ? "!" : "?"}</div><h2 id={titleId} className="mt-5 text-xl font-bold text-slate-950">{title}</h2><p id={descriptionId} className="mt-2 text-sm leading-6 text-slate-600">{description}</p><div className="mt-6 flex justify-end gap-3"><button ref={cancelRef} type="button" disabled={pending} onClick={onCancel} className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-50">{cancelLabel}</button><button ref={confirmRef} type="button" disabled={pending} onClick={onConfirm} className={`rounded-lg px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50 ${destructive ? "bg-red-600 hover:bg-red-700" : "bg-sky-600 hover:bg-sky-700"}`}>{pending ? "Working…" : confirmLabel}</button></div></section></div>, document.body);
}
