"use client";

import { useEffect, useId, useRef, useState } from "react";
import { searchHistoricalDescriptions } from "@/app/(app)/repair-orders/description-history-actions";
import { HISTORICAL_DESCRIPTION_MIN_CHARS, normalizeHistoricalDescription, type HistoricalDescriptionKind, type HistoricalDescriptionSuggestion } from "@/lib/historical-descriptions";

const DEBOUNCE_MS = 275;

export function HistoricalDescriptionCombobox({ kind, value, onChange, label = "Description", placeholder, inputClass, rowKey }: { kind: HistoricalDescriptionKind; value: string; onChange: (value: string) => void; label?: string; placeholder?: string; inputClass: string; rowKey: string }) {
  const inputId = useId(); const listboxId = useId(); const [results, setResults] = useState<HistoricalDescriptionSuggestion[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(false); const [open, setOpen] = useState(false); const [active, setActive] = useState(-1); const sequence = useRef(0); const query = normalizeHistoricalDescription(value); const eligible = query.length >= HISTORICAL_DESCRIPTION_MIN_CHARS;
  useEffect(() => {
    if (!open || !eligible) return;
    const request = ++sequence.current;
    const timer = window.setTimeout(async () => { setLoading(true); setError(false); try { const matches = await searchHistoricalDescriptions(kind, query); if (request === sequence.current) { setResults(matches); setActive(-1); } } catch { if (request === sequence.current) { setError(true); setResults([]); } } finally { if (request === sequence.current) setLoading(false); } }, DEBOUNCE_MS);
    return () => { window.clearTimeout(timer); sequence.current += 1; };
  }, [eligible, kind, open, query, rowKey]);
  const choose = (description: string) => { onChange(description); setOpen(false); setActive(-1); };
  return <label htmlFor={inputId} className="relative z-20 min-w-0 text-sm font-semibold text-slate-700 focus-within:z-40">{label}<input id={inputId} name="description" role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={listboxId} aria-activedescendant={open && active >= 0 ? `${listboxId}-${active}` : undefined} autoComplete="off" required maxLength={500} value={value} placeholder={placeholder} onFocus={() => setOpen(true)} onBlur={() => setOpen(false)} onChange={(event) => { onChange(event.target.value); setOpen(true); setActive(-1); }} onKeyDown={(event) => { if (event.key === "Escape") { setOpen(false); setActive(-1); } else if (event.key === "ArrowDown" && results.length) { event.preventDefault(); setOpen(true); setActive((index) => (index + 1) % results.length); } else if (event.key === "ArrowUp" && results.length) { event.preventDefault(); setOpen(true); setActive((index) => index > 0 ? index - 1 : results.length - 1); } else if (event.key === "Enter" && open && active >= 0) { event.preventDefault(); choose(results[active].description); } }} className={inputClass} />{open ? <div id={listboxId} role="listbox" aria-label="Previous descriptions" className="absolute left-0 z-50 mt-1 max-h-56 w-full min-w-0 overflow-y-auto rounded-lg border border-slate-200 bg-white p-1 font-normal shadow-lg">{!eligible ? <p role="status" className="px-3 py-2 text-sm text-slate-500">Type at least 2 characters</p> : loading ? <p role="status" className="px-3 py-2 text-sm text-slate-500">Searching previous descriptions…</p> : error ? <p role="status" className="px-3 py-2 text-sm text-slate-500">Previous descriptions are unavailable. Continue typing to use a new description.</p> : results.length ? results.map((result, index) => <button key={normalizeHistoricalDescription(result.description)} id={`${listboxId}-${index}`} type="button" role="option" aria-selected={active === index} onPointerDown={(event) => event.preventDefault()} onMouseEnter={() => setActive(index)} onClick={() => choose(result.description)} className={`block w-full rounded-md px-3 py-2 text-left text-sm focus:outline-none focus:ring-2 focus:ring-inset focus:ring-brand-primary/30 ${active === index ? "bg-brand-subtle text-brand-primary" : "text-slate-700 hover:bg-slate-50"}`}>{result.description}</button>) : <div className="px-3 py-2 text-sm text-slate-500"><p>No previous descriptions found</p><p className="mt-1 text-xs">Continue typing to use a new description</p></div>}</div> : null}</label>;
}
