"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { voidInvoice } from "@/app/(app)/invoices/void-actions";
import { INVOICE_VOID_REASON_OPTIONS, type VoidInvoiceState } from "@/lib/invoice-void";

const initial: VoidInvoiceState = { status: "idle" };
const reasons = INVOICE_VOID_REASON_OPTIONS.map(({ value, label }) => [value, label] as const);

export function VoidInvoiceButton({ invoiceId, invoiceNumber, originalTotal }: { invoiceId: string; invoiceNumber: string; originalTotal: string }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [reason, setReason] = useState("");
  const [state, setState] = useState<VoidInvoiceState>(initial); const [pending, startTransition] = useTransition();
  function submit(formData: FormData) { startTransition(async () => { const result = await voidInvoice(initial, formData); setState(result); if (result.status === "success") { setOpen(false); router.refresh(); } }); }
  return <><button type="button" onClick={() => setOpen(true)} className="rounded-lg border border-red-300 bg-white px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-700 hover:text-white focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-red-200">Void Invoice</button>
    {state.status === "success" ? <p role="status" className="text-sm text-emerald-700">{state.message}</p> : null}
    {open ? <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><button type="button" aria-label="Cancel void" disabled={pending} onClick={() => setOpen(false)} className="absolute inset-0 bg-slate-950/50" /><section role="alertdialog" aria-modal="true" className="relative w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-bold text-slate-950">Void Invoice {invoiceNumber}?</h2><p className="mt-3 text-sm font-semibold">Original invoice total: {originalTotal}</p><div className="mt-4 rounded-lg bg-amber-50 p-4 text-sm text-amber-950"><p>Voiding sets balance due and current AR effect to $0.00, excludes this transaction from sales and tax reporting, and prevents additional payments.</p><p className="mt-2">The original invoice and all line items remain preserved for history.</p></div><form action={submit} className="mt-5 space-y-4"><input type="hidden" name="invoiceId" value={invoiceId} /><label className="block text-sm font-semibold">Reason<select name="reason" required value={reason} onChange={(event) => setReason(event.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5"><option value="">Select a reason</option>{reasons.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="block text-sm font-semibold">{reason === "OTHER" ? "Note (required)" : "Optional note"}<textarea name="note" required={reason === "OTHER"} minLength={reason === "OTHER" ? 3 : undefined} maxLength={500} rows={3} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2" /></label>{state.status === "error" ? <p role="alert" className="text-sm text-red-700">{state.message}</p> : null}<div className="flex justify-end gap-3"><button type="button" disabled={pending} onClick={() => setOpen(false)} className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={pending} className="rounded-lg bg-red-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-red-800">{pending ? "Voiding…" : "Void Invoice"}</button></div></form></section></div> : null}</>;
}
