import type { Metadata } from "next";
import Link from "next/link";
import { getPublicShop, phoneHref, shopAddress } from "@/lib/marketing";
import { marketingServices } from "@/lib/marketing-services";
import { TrackedCallLink } from "@/components/marketing/tracked-call-link";

export const metadata: Metadata = { title: "Local Auto Repair", description: "Clear estimates, thoughtful diagnostics, and convenient auto repair appointment requests." };

export default async function MarketingHome() {
  const shop = await getPublicShop();
  const address = shopAddress(shop);
  const jsonLd = { "@context": "https://schema.org", "@type": "AutoRepair", name: shop.name, ...(shop.phone ? { telephone: shop.phone } : {}), ...(address ? { address } : {}) };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replaceAll("<", "\\u003c") }} />
    <section className="relative overflow-hidden bg-slate-950 text-white">
      <div className="absolute inset-0 opacity-30 [background-image:radial-gradient(circle_at_75%_25%,#f97316_0,transparent_30%),linear-gradient(135deg,transparent_45%,#334155_45%,#334155_46%,transparent_46%)]" />
      <div className="relative mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 sm:py-28 lg:grid-cols-[1.2fr_.8fr] lg:px-8">
        <div><p className="text-sm font-black uppercase tracking-[0.25em] text-orange-400">Local care. Clear answers.</p><h1 className="mt-5 max-w-3xl text-5xl font-black leading-[1.02] tracking-tight sm:text-6xl">Auto repair built around trust.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Bring us the warning light, strange sound, maintenance question, or repair concern. We’ll listen, inspect, and help you understand the next step.</p><div className="mt-8 flex flex-wrap gap-3"><TrackedCallLink href={phoneHref(shop.phone)} className="rounded-xl bg-orange-500 px-5 py-3.5 font-black text-white hover:bg-orange-600">Call Now</TrackedCallLink><Link href="/appointment" className="rounded-xl bg-white px-5 py-3.5 font-black text-slate-950 hover:bg-slate-100">Schedule Appointment</Link><Link href="/drop-off" className="rounded-xl border border-slate-600 px-5 py-3.5 font-black text-white hover:border-slate-400">Request Drop-Off</Link></div></div>
        <div className="self-end rounded-3xl border border-white/10 bg-white/5 p-7 backdrop-blur"><p className="text-sm font-black uppercase tracking-widest text-orange-400">Plan your visit</p><dl className="mt-5 space-y-5 text-sm"><div><dt className="text-slate-400">Shop</dt><dd className="mt-1 text-lg font-bold">{shop.name}</dd></div><div><dt className="text-slate-400">Location</dt><dd className="mt-1 font-semibold">{address || "Contact us for directions"}</dd></div><div><dt className="text-slate-400">Hours</dt><dd className="mt-1 font-semibold">{shop.hours}</dd></div></dl></div>
      </div>
    </section>
    <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="flex items-end justify-between gap-5"><div><p className="text-sm font-black uppercase tracking-widest text-orange-600">What we do</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Care for the miles ahead</h2></div><Link href="/services" className="hidden font-bold text-orange-600 sm:block">View all services →</Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{marketingServices.slice(0, 4).map((service) => <Link key={service.slug} href={`/services/${service.slug}`} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm hover:-translate-y-1 hover:border-orange-200 hover:shadow-md"><span className="text-2xl text-orange-500">◆</span><h3 className="mt-5 text-lg font-black group-hover:text-orange-600">{service.name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{service.summary}</p></Link>)}</div></section>
    <section className="bg-white"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="text-center"><p className="text-sm font-black uppercase tracking-widest text-orange-600">Why choose us</p><h2 className="mt-3 text-3xl font-black tracking-tight">A better repair conversation</h2></div><div className="mt-10 grid gap-6 md:grid-cols-4">{[["Honest diagnostics","Testing focused on the concern, with findings you can understand."],["Clear estimates","Review the recommendation and cost before authorized work begins."],["Local repair shop","A nearby team invested in lasting customer relationships."],["Service history support","Organized records help make future maintenance decisions easier."]].map(([title, text]) => <div key={title} className="rounded-2xl bg-stone-50 p-6"><h3 className="font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>)}</div></div></section>
    <section className="mx-auto grid max-w-7xl gap-6 px-4 py-20 sm:px-6 lg:grid-cols-2 lg:px-8"><div className="rounded-3xl bg-orange-500 p-8 text-white sm:p-10"><p className="text-sm font-black uppercase tracking-widest text-orange-100">Seasonal savings</p><h2 className="mt-4 text-3xl font-black">Simple offers, no mystery fine print.</h2><p className="mt-3 leading-7 text-orange-50">See current sample offers and ask the shop which one fits your visit.</p><Link href="/coupons" className="mt-7 inline-block rounded-xl bg-white px-5 py-3 font-black text-orange-600">View Coupons</Link></div><div className="rounded-3xl bg-slate-900 p-8 text-white sm:p-10"><p className="text-sm font-black uppercase tracking-widest text-slate-400">Customer perspective</p><blockquote className="mt-4 text-2xl font-bold leading-9">“Use this space for a verified customer review once the shop approves it.”</blockquote><Link href="/reviews" className="mt-7 inline-block font-bold text-orange-400">Reviews and feedback →</Link></div></section>
    <section className="border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-16 sm:px-6 md:grid-cols-[1fr_auto] md:items-center lg:px-8"><div><h2 className="text-3xl font-black tracking-tight">Ready to talk about your vehicle?</h2><p className="mt-3 text-slate-600">Send a request and the shop can follow up with availability and next steps.</p></div><Link href="/appointment" className="rounded-xl bg-orange-500 px-6 py-3.5 text-center font-black text-white">Request an Appointment</Link></div></section>
  </>;
}
