import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getMarketingServices } from "@/lib/marketing-content";
import { marketingServices } from "@/lib/marketing-services";

export function generateStaticParams() { return marketingServices.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const slug = (await params).slug; const service = (await getMarketingServices()).find((item) => item.slug === slug); return service ? { title: service.name, description: service.summary } : {}; }
export default async function ServiceDetail({ params }: { params: Promise<{ slug: string }> }) { const slug = (await params).slug; const service = (await getMarketingServices()).find((item) => item.slug === slug); if (!service) notFound(); return <section className="mx-auto max-w-5xl px-4 py-20 sm:px-6"><Link href="/services" className="text-sm font-bold text-orange-600">← All services</Link><div className="mt-8 grid gap-10 lg:grid-cols-[1fr_320px]"><div><p className="text-xs font-black uppercase tracking-[0.25em] text-orange-600">Vehicle service</p><h1 className="mt-4 text-5xl font-black tracking-tight">{service.name}</h1><p className="mt-6 text-xl leading-9 text-slate-600">{service.detail}</p><h2 className="mt-10 text-2xl font-black">What to expect</h2><ul className="mt-5 space-y-3 text-slate-600"><li>• A conversation about symptoms, timing, and priorities.</li><li>• An inspection or test appropriate to the concern.</li><li>• A clear recommendation and estimate before authorized work.</li><li>• Service history retained for future visits.</li></ul></div><aside className="rounded-3xl bg-slate-950 p-7 text-white"><p className="text-sm font-black uppercase tracking-widest text-orange-400">Need this service?</p><p className="mt-4 text-sm leading-6 text-slate-300">Tell the shop about your vehicle and preferred timing.</p><Link href={`/appointment?service=${service.slug}`} className="mt-6 block rounded-xl bg-orange-500 px-5 py-3 text-center font-black">Request Appointment</Link><Link href="/contact" className="mt-3 block rounded-xl border border-slate-700 px-5 py-3 text-center font-bold">Ask a Question</Link></aside></div></section>; }
